#!/bin/sh
alias \
    v="$EDITOR" \
    vi="$EDITOR" \
    vim="$EDITOR" \
    sudo="doas" \
    stow="stow --dotfiles" \
    stowsync="stowsync.sh" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    g="git" \
    k="killall" \
    mk="make" \
    i="info --vi-keys" \
    info="info --vi-keys" \
    mkd="mkdir -pv" \
    shd="sudo shutdown -h now" \
    mdf="mednafen" \
    n64="mupen64plus" \
    mpv="mpv --save-position-on-quit --no-sub-ass" \
    rm="echo Use the full path i.e. '/bin/rm', consider using trash" \
    trash="trash --verbose" \
    scrk="screenkey --no-whitespace -s small --bak-mode full -t 1 &" \
    showme="webcam.sh" \
    mpp="mpv --no-video --playlist-shuffle ~/Music" \
    mpa="mpv --playlist-shuffle ~/Music" \
    enc="gpg -c --no-symkey-cache --cipher-algo AES256" \
    ytv="yt-dlp -i" \
    yta="yt-dlp -x -f bestaudio[ext=opus]/best[ext=opus]" \
    ytt="yt --write-thumbnail" \
    d="devour" \
    mpv="d mpv" \
    zathura="d zathura" \
    nsxiv="d nsxiv" \
    ls="ls -hN --color=auto --group-directories-first" \
    lk="ls -hN --color=auto --group-directories-first -ak" \
    la="ls -hN --color=auto --group-directories-first -al" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
