wireplumber.settings = {
    # set default system output volume to 50%
    device.routes.default-sink-volume = 0.2
    # set default playback stream volume to 50%
    node.stream.default-playback-volume = 0.5
    # dont restore stream properties
    stream.properties.restore.props = false
}
