# Loop webms
[extension.webm]
loop-file=inf

# NOTE: all configuration after a profile([...]) is set
# is considered as to be applied to that runtime profile
# specifically. make sure to seperate runtime profiles correctly
# or you'll get configured volume only in webms like stupid ol' me
# :)
[default]
# Youtube Support
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bestvideo[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best

# Subtitle Configuration
sub-font-size=30
sub-auto=all

# Hardware Acceleration
hwdec=auto

# Audio Configuration
ao=pipewire
volume=50
volume-max=100
