# Loop webms
[extension.webm]
loop-file=inf

# NOTE: all configuration after a profile([...]) is set
# is considered as to be applied to that runtime profile
# specifically. make sure to seperate runtime profiles correctly
# or you'll get configured volume only in webms like stupid ol' me
# :)
[default]
# Youtube Support
script-opts=ytdl_hook-ytdl_path=yt-dlp
#age-restrict bypass
ytdl-raw-options=cookies-from-browser=firefox:$HOME/.librewolf/
#resolution and audio
ytdl-format=bestvideo[height=1080p][vcodec^=vp9]+bestaudio[acodec^=opus]/bestvideo[height<=?1080p][vcodec^=avc1]+bestaudio/bestvideo+bestaudio/best

# Subtitle Configuration
sub-font-size=30
sub-auto=fuzzy #load only filename matching subtitles
alang='jpn,jp,eng,en' #priority seq of audio tracks
slang='eng,en,enUS,jpn,jp' #priority seq of subtitles

# Hardware Acceleration
hwdec=auto

# Audio Configuration
ao=pipewire
volume=50
volume-max=100
