#!/bin/sh
alias \
    v="$EDITOR" \
    sudo="doas" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    g="git" \
    k="kill" \
    mk="make" \
    m="man" \
    i="info --vi-keys" \
    info="info --vi-keys" \
    mkd="mkdir -pv" \
    shd="sudo shutdown -h now" \
    trm="transmission-remote" \
    mdf="mednafen" \
    n64="mupen64plus" \
    mpv="mpv --no-sub-ass" \
    scrk="screenkey --no-whitespace -s small --bak-mode full -t 1 &" \
    showme="mpv --no-osc --autofit=30% /dev/video0" \
    mpp="mpv -playlist="."" \
    enc="gpg -c --no-symkey-cache --cipher-algo AES256" \
    yt="yt-dlp --add-metadata -i" \
    yta="yt-dlp -x -f bestaudio[ext=opus]/best[ext=opus]" \
    ytt="yt --write-thumbnail" \
    sdl="spotdl --format opus" \
    d="devour" \
    mpv="d mpv" \
    zathura="d zathura" \
    nsxiv="d nsxiv" \
    ls="ls -hN --color=auto --group-directories-first" \
    lk="ls -hN --color=auto --group-directories-first -ak" \
    la="ls -hN --color=auto --group-directories-first -al" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
