#!/bin/sh
alias \
    v="$EDITOR" \
    sudo="doas" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mk="make" \
    g="git" \
    mkd="mkdir -pv" \
    shd="sudo shutdown -h now" \
    trm="transmission-remote" \
    emacs="emacsclient -nw -ca $EDITOR" \
    mdf="mednafen" \
    n64="mupen64plus" \
    mpv="mpv --no-sub-ass" \
    scrk="screenkey --no-whitespace -s small --bak-mode full -t 1 &" \
    showme="mpv --no-osc --autofit=30% /dev/video0" \
    mpp="mpv -playlist=".'' \
    enc="gpg -c --no-symkey-cache --cipher-algo AES256" \
    yt="yt-dlp --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ytt="yt --write-thumbnail" \
    mpv="swallow mpv" \
    ffplay="swallow ffplay" \
    zathura="swallow zathura" \
    nsxiv="swallow nsxiv" \
    ls="ls -hN --color=auto --group-directories-first" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
