#!/bin/sh

# Shortening common commands and making some more verbose.
alias \
	e="$EDITOR" \
	v="$EDITOR" \
    sudo="doas" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
    mk="make" \
	g="git" \
	mkd="mkdir -pv" \
    shdn="sudo shutdown -h now" \
	yt="yt-dlp --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	trm="transmission-remote" \
    session="./session" \
    ani-cli="cd /usr/local/bin/ && ./ani-cli" \
    mpp="mpv -playlist='.'" \
    mdf="mednafen" \
    n64="mupen64plus" \
    mpv="mpv --no-sub-ass" \

# adding color to commands.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
    dir="dir --color=auto" \
    vdir="vdir --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
